"""Self-test for the cross-language hash fixture file.

This file is the Python half of the SPEC §3.9 / T12 byte-identity contract.
The TS half lives at
``.obsidian/plugins/obsidian-render-cache/tests/hash.test.ts``.

The fixture itself (``tests/fixtures/hash_fixtures.json``, generated by
``tests/generate_hash_fixtures.py``) is the single source of truth. This test
re-derives every key in Python and asserts it equals the stored
``expectedKey``. A red here means the Python side regressed: either
``compute_key`` or ``normalize`` was changed in a non-byte-identical way.

If this test goes red:

1. If the change to ``hash.py`` / ``normalize.py`` was deliberate, regenerate
   the fixture with ``python3 -m tests.generate_hash_fixtures`` and commit
   atomically with the corresponding ``hash.ts`` change.
2. The TS test will go red simultaneously until the TS port is updated.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from render_cache.hash import compute_key

REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURE_PATH = (
    REPO_ROOT
    / ".obsidian"
    / "plugins"
    / "obsidian-render-cache"
    / "tests"
    / "fixtures"
    / "hash_fixtures.json"
)


def _load() -> list[dict]:
    if not FIXTURE_PATH.exists():
        pytest.fail(
            f"hash fixture missing at {FIXTURE_PATH}. "
            "Run: python3 -m tests.generate_hash_fixtures"
        )
    data = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    assert data["schemaVersion"] == 1, "schema bump requires test review"
    return data["fixtures"]


def test_fixture_file_exists_and_loads():
    fixtures = _load()
    assert len(fixtures) >= 10, "AC8.6 mandates at least 10 fixtures"


@pytest.mark.parametrize("fixture", _load(), ids=lambda f: f["name"])
def test_python_compute_key_matches_fixture(fixture: dict):
    actual = compute_key(
        fixture["source"],
        fixture["language"],
        fixture["attrs"],
        fixture["preambleHash"],
    )
    assert actual == fixture["expectedKey"], (
        f"hash drift in fixture '{fixture['name']}': "
        f"expected {fixture['expectedKey']}, got {actual}. "
        f"Either Python's compute_key changed (regenerate fixture and "
        f"update TS port) or the fixture file is stale."
    )


def test_fixture_keys_are_all_distinct_where_expected():
    """Two fixtures share the same hash by design (CRLF and lone-CR both
    canonicalize to LF), so the *count* matters, not pure uniqueness."""
    fixtures = _load()
    keys = [f["expectedKey"] for f in fixtures]
    # crlf_line_endings + lone_cr_line_endings -> identical content post-normalize
    duplicates = {k for k in keys if keys.count(k) > 1}
    expected_dupes = {
        compute_key("line one\nline two\nline three", "graphviz", {}, "0000000000000000")
    }
    assert duplicates == expected_dupes, (
        f"unexpected hash collision among fixtures: {duplicates - expected_dupes}"
    )


def test_per_line_strip_fixture_proves_python_uses_full_strip():
    """Guards against the PLAN.md §Phase 8 trimEnd() bug: if the Python
    normalize ever switched to trimEnd(), this fixture's expectedKey would
    silently change. The TS port must use full strip(), not trimEnd().
    """
    fixtures = {f["name"]: f for f in _load()}
    f = fixtures["per_line_whitespace_strip"]
    # The literal source has both leading AND trailing whitespace per line.
    # If Python switched to trimEnd, the leading spaces would survive into
    # the hash payload and the expectedKey would change.
    assert f["source"] == "    leading  \n  middle  \n   trailing  "
    actual = compute_key(f["source"], f["language"], f["attrs"], f["preambleHash"])
    assert actual == f["expectedKey"]


def test_attrs_single_key_fixture_documents_python_json_spacing():
    """Guards the JSON-stringify-spaces divergence. Python json.dumps emits
    '{"k": "v"}' (with space after colon); JS JSON.stringify emits
    '{"k":"v"}'. The TS port must replicate Python's spacing in its own
    pythonJsonDumps helper, or this fixture will go red on the TS side
    (Phase 9+ when attrs become non-empty in production)."""
    fixtures = {f["name"]: f for f in _load()}
    f = fixtures["attrs_single_key_PYTHON_JSON_SPACES"]
    assert f["attrs"] == {"k": "v"}
    actual = compute_key(f["source"], f["language"], f["attrs"], f["preambleHash"])
    assert actual == f["expectedKey"]
