/**
 * Cross-language hash byte-identity test (T12 contract).
 *
 * Reads tests/fixtures/hash_fixtures.json — generated by Python via
 * `python3 -m tests.generate_hash_fixtures` from
 * resources/scripts/python_single/tests/generate_hash_fixtures.py — and
 * asserts the TS port produces the same hash as the canonical Python
 * compute_key (SPEC §3.9).
 *
 * If this test goes red AFTER a deliberate change to Python's hash.py /
 * normalize.py: regenerate the fixture, then update hash.ts to match.
 *
 * If this test goes red WITHOUT a Python-side change: the TS port has
 * regressed.
 */
import { computeKey, normalize, pythonJsonDumps } from "../src/hash";
import * as fs from "fs";
import * as path from "path";

interface Fixture {
  name: string;
  description: string;
  source: string;
  language: string;
  attrs: Record<string, unknown>;
  preambleHash: string;
  expectedKey: string;
}

interface FixtureFile {
  schemaVersion: number;
  rendererVersion: string;
  description: string;
  fixtures: Fixture[];
}

const FIXTURE_PATH = path.resolve(__dirname, "fixtures/hash_fixtures.json");

function loadFixtures(): FixtureFile {
  if (!fs.existsSync(FIXTURE_PATH)) {
    throw new Error(
      `hash fixture missing at ${FIXTURE_PATH}. Run: python3 -m tests.generate_hash_fixtures`,
    );
  }
  const raw = fs.readFileSync(FIXTURE_PATH, "utf-8");
  return JSON.parse(raw) as FixtureFile;
}

describe("normalize() byte-equivalence", () => {
  test("strips per-line whitespace on BOTH ends (not just trailing)", () => {
    // The PLAN.md §Phase 8 pseudocode said `.trimEnd()` — that's wrong.
    // Python's normalize uses `ln.strip()`. This test pins the correct rule.
    expect(normalize("  hello  \n  world  ")).toBe("hello\nworld");
  });

  test("CRLF and lone CR canonicalize to LF", () => {
    expect(normalize("a\r\nb")).toBe("a\nb");
    expect(normalize("a\rb")).toBe("a\nb");
  });

  test("collapses multi-blank-line runs to a single blank line", () => {
    expect(normalize("first\n\n\n\n\nsecond")).toBe("first\n\nsecond");
  });

  test("strips leading + trailing blank lines", () => {
    expect(normalize("\n\nhello\n\n")).toBe("hello");
  });

  test("all-whitespace input collapses to empty string", () => {
    expect(normalize("   \n   \n")).toBe("");
  });
});

describe("pythonJsonDumps() — Python json.dumps compatibility", () => {
  test("empty object produces '{}' (matches both Python and JS)", () => {
    expect(pythonJsonDumps({})).toBe("{}");
  });

  test("single key includes space after colon (Python default separator)", () => {
    expect(pythonJsonDumps({ k: "v" })).toBe('{"k": "v"}');
  });

  test("multi-key sorts keys alphabetically", () => {
    expect(pythonJsonDumps({ zeta: "z", alpha: "a", mu: "m" })).toBe(
      '{"alpha": "a", "mu": "m", "zeta": "z"}',
    );
  });

  test("nested arrays preserve Python spacing", () => {
    expect(pythonJsonDumps({ a: 1, b: [1, 2] })).toBe('{"a": 1, "b": [1, 2]}');
  });
});

describe("computeKey() — cross-language byte-identity (T12)", () => {
  const file = loadFixtures();

  test("at least 10 fixtures present (AC8.6 mandate)", () => {
    expect(file.fixtures.length).toBeGreaterThanOrEqual(10);
  });

  for (const fx of file.fixtures) {
    test(`${fx.name}: ${fx.description.slice(0, 60)}…`, async () => {
      const key = await computeKey(fx.source, fx.language, fx.attrs, fx.preambleHash);
      expect(key).toBe(fx.expectedKey);
    });
  }
});
